
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class DELETE_CONTACT extends javax.swing.JFrame {

    /**
     * Creates new form delete_contact
     */
    public DELETE_CONTACT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NAME_LABEL = new javax.swing.JLabel();
        NAME = new javax.swing.JTextField();
        ADDRESS_LABEL = new javax.swing.JLabel();
        ADDRESS = new javax.swing.JScrollPane();
        ADDRESS_F = new javax.swing.JTextArea();
        GROUP_LABEL = new javax.swing.JLabel();
        DELETE = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        GROUP = new javax.swing.JTextField();
        dob_label = new javax.swing.JLabel();
        DOB = new javax.swing.JTextField();
        EMAIL_TABLE = new javax.swing.JScrollPane();
        EMAIL = new javax.swing.JTable();
        MOBILE_TABLE = new javax.swing.JScrollPane();
        MOBILE = new javax.swing.JTable();
        NAME_BOX = new javax.swing.JComboBox();
        DELETE_LABEL = new javax.swing.JLabel();
        BACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/address2.jpg"))); // NOI18N

        jPanel1.setLayout(null);

        NAME_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NAME_LABEL.setText("NAME");
        jPanel1.add(NAME_LABEL);
        NAME_LABEL.setBounds(330, 70, 40, 15);

        NAME.setEditable(false);
        jPanel1.add(NAME);
        NAME.setBounds(450, 60, 230, 30);

        ADDRESS_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ADDRESS_LABEL.setText("ADDRESS");
        jPanel1.add(ADDRESS_LABEL);
        ADDRESS_LABEL.setBounds(330, 120, 70, 15);

        ADDRESS_F.setEditable(false);
        ADDRESS_F.setColumns(20);
        ADDRESS_F.setLineWrap(true);
        ADDRESS_F.setRows(5);
        ADDRESS_F.setWrapStyleWord(true);
        ADDRESS.setViewportView(ADDRESS_F);

        jPanel1.add(ADDRESS);
        ADDRESS.setBounds(450, 110, 230, 90);

        GROUP_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GROUP_LABEL.setText("GROUP");
        jPanel1.add(GROUP_LABEL);
        GROUP_LABEL.setBounds(330, 230, 60, 15);

        DELETE.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DELETE.setText("DELETE CONTACT");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE);
        DELETE.setBounds(20, 170, 200, 30);

        BACK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel1.add(BACK);
        BACK.setBounds(60, 260, 110, 30);

        GROUP.setEditable(false);
        jPanel1.add(GROUP);
        GROUP.setBounds(450, 220, 230, 30);

        dob_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dob_label.setText("DATE OF BIRTH");
        dob_label.setToolTipText("yyyy-mm-dd");
        jPanel1.add(dob_label);
        dob_label.setBounds(330, 280, 100, 15);

        DOB.setEditable(false);
        DOB.setToolTipText("yyyy-mm-dd");
        jPanel1.add(DOB);
        DOB.setBounds(449, 270, 230, 30);

        EMAIL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EMAIL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MOBILE NUMBERS"
            }
        ));
        EMAIL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMAILMouseClicked(evt);
            }
        });
        EMAIL_TABLE.setViewportView(EMAIL);

        jPanel1.add(EMAIL_TABLE);
        EMAIL_TABLE.setBounds(210, 320, 210, 120);

        MOBILE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MOBILE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EMAIL IDs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MOBILE_TABLE.setViewportView(MOBILE);

        jPanel1.add(MOBILE_TABLE);
        MOBILE_TABLE.setBounds(450, 320, 230, 120);

        NAME_BOX.setModel(new DefaultComboBoxModel());
        NAME_BOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME_BOXActionPerformed(evt);
            }
        });
        jPanel1.add(NAME_BOX);
        NAME_BOX.setBounds(30, 70, 180, 30);

        DELETE_LABEL.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        DELETE_LABEL.setText("DELETING A CONTACT");
        jPanel1.add(DELETE_LABEL);
        DELETE_LABEL.setBounds(230, 10, 270, 30);

        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jPanel1.add(BACKGROUND);
        BACKGROUND.setBounds(0, 0, 720, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try
       {
           DefaultComboBoxModel model=(DefaultComboBoxModel)NAME_BOX.getModel();
           Class.forName("java.sql.Driver");
           String q1="";
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost/address","root","modi");
           Statement stmt=con.createStatement();      
           q1=" select concat(first_name,' ',middle_name,' ',last_name,' ','(',(contact_id),')') from contact order by first_name;";
           ResultSet rs=stmt.executeQuery(q1);
           model.removeAllElements();
           while(rs.next())
           {
               String c=rs.getString("concat(first_name,' ',middle_name,' ',last_name,' ','(',(contact_id),')')");
               model.addElement(c);
           }
           
       }
    catch(Exception e)
       {
        JOptionPane.showMessageDialog(this, e.getMessage());
       }
    }//GEN-LAST:event_formWindowOpened

    private void NAME_BOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME_BOXActionPerformed
       try
        {
            String mi="";
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/address","root","modi");
            Statement stmt=(Statement)con.createStatement();
            String st=(String)NAME_BOX.getSelectedItem();
            int l=st.length();
            String s=st.substring(l-6,l-1);
            DefaultTableModel model1=(DefaultTableModel)EMAIL.getModel();
            DefaultTableModel model2=(DefaultTableModel)MOBILE.getModel();
            String query="select * from contact where contact_id='"+s+"';";
            ResultSet rs1=stmt.executeQuery(query);            
            rs1.next();
            String ci=rs1.getString("contact_id");
            String fn=rs1.getString("first_name");
            String mn=rs1.getString("middle_name");
            String ln=rs1.getString("last_name");     NAME.setText(fn+" "+mn+" "+ln);
            String gr=rs1.getString("groups");        GROUP.setText(gr);
            String ad1=rs1.getString("add_line1");
            String ad2=rs1.getString("add_line2");
            String city=rs1.getString("city");
            String state=rs1.getString("state");      
            String pin=rs1.getString("pin");          ADDRESS_F.setText(ad1+" "+ad2+" "+city+" "+state+" "+pin);
            String dob=rs1.getString("dob");          DOB.setText(dob);
            String q1="select mob_number from mobile where contact_id='"+(ci)+"';";
            String q2="select email_id from email where contact_id='"+(ci)+"';";
            int n1=model1.getRowCount();
            for( int i=1;i<=n1;i++)
            {
                model1.removeRow(0);
            }    
            int n2=model2.getRowCount();
            for( int i=1;i<=n2;i++)
            {
                model2.removeRow(0);
            }   
            ResultSet rs2=stmt.executeQuery(q1);
            while(rs2.next())
            {
                String mob=rs2.getString("mob_number");
                model1.addRow(new Object[]{mob});
            }
            ResultSet rs3=stmt.executeQuery(q2);
            while(rs3.next())
            {
                String em=rs3.getString("email_id");
                model2.addRow(new Object[]{em});
            }
            rs1.close();  rs2.close();  rs3.close();         
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }   
    }//GEN-LAST:event_NAME_BOXActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
       try
        {
           Class.forName("java.sql.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/address","root","modi");
            Statement stmt=(Statement) con.createStatement();
            int m=JOptionPane.showConfirmDialog(this,"DO YOU REALLY WANT TO DELETE THIS RECORD?","MESSAGE",JOptionPane.YES_NO_OPTION);
            if(m==0)
            {           
            String st=(String)NAME_BOX.getSelectedItem();
            int l=st.length();
            String s=st.substring(l-6,l-1);
            String q1="delete from mobile where contact_id='"+(s)+"';";
            String q2="delete from email where contact_id='"+(s)+"';";
            String query="delete from contact where contact_id='"+(s)+"';";
            stmt.executeUpdate(q1);            
            stmt.executeUpdate(q2);
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "CONTACT DELETED");
               DefaultComboBoxModel model=(DefaultComboBoxModel)NAME_BOX.getModel();
               String q3=" select concat(first_name,' ',middle_name,' ',last_name,' ','(',(contact_id),')') from contact order by first_name;";
               ResultSet rs=stmt.executeQuery(q3);
               model.removeAllElements();
               while(rs.next())
               {
                  String c=rs.getString("concat(first_name,' ',middle_name,' ',last_name,' ','(',(contact_id),')')");
                  model.addElement(c);
               }
            }
            else JOptionPane.showMessageDialog(this,"CONTACT NOT DELETED");
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,e.getMessage());
       }
        
    }//GEN-LAST:event_DELETEActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
       new FIRST_PAGE().show();
       this.dispose();
    }//GEN-LAST:event_BACKActionPerformed

    private void EMAILMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMAILMouseClicked
       
    }//GEN-LAST:event_EMAILMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DELETE_CONTACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DELETE_CONTACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DELETE_CONTACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DELETE_CONTACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DELETE_CONTACT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ADDRESS;
    private javax.swing.JTextArea ADDRESS_F;
    private javax.swing.JLabel ADDRESS_LABEL;
    private javax.swing.JButton BACK;
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JButton DELETE;
    private javax.swing.JLabel DELETE_LABEL;
    private javax.swing.JTextField DOB;
    private javax.swing.JTable EMAIL;
    private javax.swing.JScrollPane EMAIL_TABLE;
    private javax.swing.JTextField GROUP;
    private javax.swing.JLabel GROUP_LABEL;
    private javax.swing.JTable MOBILE;
    private javax.swing.JScrollPane MOBILE_TABLE;
    private javax.swing.JTextField NAME;
    private javax.swing.JComboBox NAME_BOX;
    private javax.swing.JLabel NAME_LABEL;
    private javax.swing.JLabel dob_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
