/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class SEARCH extends javax.swing.JFrame {

    /**
     * Creates new form page
     */
    public SEARCH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        SEARCH_NAME = new javax.swing.JButton();
        SEARCH_GROUP = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        title_label = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/address2.jpg"))); // NOI18N

        jPanel1.setLayout(null);

        SEARCH_NAME.setBackground(new java.awt.Color(0, 255, 255));
        SEARCH_NAME.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SEARCH_NAME.setText("SEARCH BY NAME");
        SEARCH_NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_NAMEActionPerformed(evt);
            }
        });
        jPanel1.add(SEARCH_NAME);
        SEARCH_NAME.setBounds(70, 160, 210, 50);

        SEARCH_GROUP.setBackground(new java.awt.Color(0, 255, 255));
        SEARCH_GROUP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SEARCH_GROUP.setText("SEARCH BY GROUP");
        SEARCH_GROUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_GROUPActionPerformed(evt);
            }
        });
        jPanel1.add(SEARCH_GROUP);
        SEARCH_GROUP.setBounds(440, 160, 210, 50);

        BACK.setBackground(new java.awt.Color(0, 255, 255));
        BACK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel1.add(BACK);
        BACK.setBounds(70, 300, 210, 50);

        EXIT.setBackground(new java.awt.Color(0, 255, 255));
        EXIT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT);
        EXIT.setBounds(440, 300, 210, 50);

        title_label.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        title_label.setForeground(new java.awt.Color(51, 51, 51));
        title_label.setText("SEARCH FOR A CONTACT");
        jPanel1.add(title_label);
        title_label.setBounds(130, 30, 470, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
       new FIRST_PAGE().show();
       this.dispose();
    }//GEN-LAST:event_BACKActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void SEARCH_GROUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_GROUPActionPerformed
       new SEARCH_GROUP().show();
       this.dispose();
    }//GEN-LAST:event_SEARCH_GROUPActionPerformed

    private void SEARCH_NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_NAMEActionPerformed
       new SEARCH_NAME().show();
       this.dispose();
    }//GEN-LAST:event_SEARCH_NAMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEARCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEARCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEARCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEARCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEARCH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton SEARCH_GROUP;
    private javax.swing.JButton SEARCH_NAME;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
}
