
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class SEARCH_GROUP extends javax.swing.JFrame {

    /**
     * Creates new form SEARCH_GROUP
     */
    public SEARCH_GROUP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        GROUP = new javax.swing.JScrollPane();
        GROUPS = new javax.swing.JList();
        NAMES = new javax.swing.JComboBox();
        NAME_LABEL = new javax.swing.JLabel();
        NAME = new javax.swing.JTextField();
        ADDRESS_LABEL = new javax.swing.JLabel();
        ADDRESS = new javax.swing.JScrollPane();
        ADDRESS_F = new javax.swing.JTextArea();
        GROUP_LABEL = new javax.swing.JLabel();
        GROUP1 = new javax.swing.JTextField();
        dob_label = new javax.swing.JLabel();
        DOB = new javax.swing.JTextField();
        EMAIL_TABLE = new javax.swing.JScrollPane();
        EMAIL = new javax.swing.JTable();
        MOBILE_TABLE = new javax.swing.JScrollPane();
        MOBILE = new javax.swing.JTable();
        EXIT = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        SEARCH_LABEL = new javax.swing.JLabel();
        CANVAS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/address2.jpg"))); // NOI18N

        jPanel1.setLayout(null);

        GROUPS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GROUPS.setModel(new DefaultListModel());
        GROUPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GROUPSMouseClicked(evt);
            }
        });
        GROUPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GROUPSKeyTyped(evt);
            }
        });
        GROUP.setViewportView(GROUPS);

        jPanel1.add(GROUP);
        GROUP.setBounds(10, 110, 90, 170);

        NAMES.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NAMES.setModel(new DefaultComboBoxModel());
        NAMES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NAMESMouseClicked(evt);
            }
        });
        NAMES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMESActionPerformed(evt);
            }
        });
        jPanel1.add(NAMES);
        NAMES.setBounds(120, 110, 160, 30);

        NAME_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NAME_LABEL.setText("NAME");
        jPanel1.add(NAME_LABEL);
        NAME_LABEL.setBounds(330, 70, 40, 15);

        NAME.setEditable(false);
        jPanel1.add(NAME);
        NAME.setBounds(450, 60, 230, 30);

        ADDRESS_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ADDRESS_LABEL.setText("ADDRESS");
        jPanel1.add(ADDRESS_LABEL);
        ADDRESS_LABEL.setBounds(330, 120, 70, 15);

        ADDRESS_F.setEditable(false);
        ADDRESS_F.setColumns(20);
        ADDRESS_F.setLineWrap(true);
        ADDRESS_F.setRows(5);
        ADDRESS_F.setWrapStyleWord(true);
        ADDRESS.setViewportView(ADDRESS_F);

        jPanel1.add(ADDRESS);
        ADDRESS.setBounds(450, 110, 230, 90);

        GROUP_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GROUP_LABEL.setText("GROUP");
        jPanel1.add(GROUP_LABEL);
        GROUP_LABEL.setBounds(330, 230, 60, 15);

        GROUP1.setEditable(false);
        jPanel1.add(GROUP1);
        GROUP1.setBounds(450, 220, 230, 30);

        dob_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dob_label.setText("DATE OF BIRTH");
        dob_label.setToolTipText("yyyy-mm-dd");
        jPanel1.add(dob_label);
        dob_label.setBounds(330, 280, 100, 15);

        DOB.setEditable(false);
        DOB.setToolTipText("yyyy-mm-dd");
        jPanel1.add(DOB);
        DOB.setBounds(449, 270, 230, 30);

        EMAIL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EMAIL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MOBILE NUMBERS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EMAIL_TABLE.setViewportView(EMAIL);

        jPanel1.add(EMAIL_TABLE);
        EMAIL_TABLE.setBounds(210, 320, 210, 120);

        MOBILE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MOBILE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EMAIL IDs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MOBILE_TABLE.setViewportView(MOBILE);

        jPanel1.add(MOBILE_TABLE);
        MOBILE_TABLE.setBounds(450, 320, 230, 120);

        EXIT.setBackground(new java.awt.Color(0, 255, 255));
        EXIT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT);
        EXIT.setBounds(20, 410, 100, 30);

        BACK.setBackground(new java.awt.Color(0, 255, 255));
        BACK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel1.add(BACK);
        BACK.setBounds(20, 330, 100, 30);

        SEARCH_LABEL.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        SEARCH_LABEL.setText("SEARCH BY GROUP");
        jPanel1.add(SEARCH_LABEL);
        SEARCH_LABEL.setBounds(190, 10, 340, 40);

        CANVAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jPanel1.add(CANVAS);
        CANVAS.setBounds(0, 0, 720, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try
       {
           DefaultListModel model=(DefaultListModel)GROUPS.getModel();
           Class.forName("java.sql.Driver");
           String q1="";
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost/address","root","modi");
           Statement stmt=con.createStatement();      
           q1="select distinct groups from contact;";
           ResultSet rs=stmt.executeQuery(q1);
           model.removeAllElements();
           while(rs.next())
           {
               String c=rs.getString("groups");
               model.addElement(c);
           }
           
       }
    catch(Exception e)
       {
        JOptionPane.showMessageDialog(this, e.getMessage());
       }
    }//GEN-LAST:event_formWindowOpened

    private void GROUPSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GROUPSKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_GROUPSKeyTyped

    private void GROUPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GROUPSMouseClicked
     try
       {
           DefaultComboBoxModel model1=(DefaultComboBoxModel)NAMES.getModel();
           String g=(String)GROUPS.getSelectedValue();
           Class.forName("java.sql.Driver");
           String q2="";
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost/address","root","modi");
           Statement stmt=con.createStatement();      
           q2="select concat(first_name,' ',middle_name,' ',last_name) from contact where groups='"+(g)+"';";
           ResultSet rs=stmt.executeQuery(q2);
           model1.removeAllElements();
           while(rs.next())
           {
               String c=rs.getString("concat(first_name,' ',middle_name,' ',last_name)");
               model1.addElement(c);
           }
           
       }
    catch(Exception e)
       {
        JOptionPane.showMessageDialog(this, e.getMessage());
       }
    }//GEN-LAST:event_GROUPSMouseClicked

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void NAMESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NAMESMouseClicked
       
    }//GEN-LAST:event_NAMESMouseClicked

    private void NAMESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMESActionPerformed
      if(NAMES.isShowing()==true)
      {
          
      try
        {
            String mi="";
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/address","root","modi");
            Statement stmt=(Statement)con.createStatement();
            String st=(String)NAMES.getSelectedItem();
            DefaultTableModel model1=(DefaultTableModel)EMAIL.getModel();
            DefaultTableModel model2=(DefaultTableModel)MOBILE.getModel();
            String query="select * from contact where concat(first_name,' ',middle_name,' ',last_name)='"+st+"';";
            ResultSet rs1=stmt.executeQuery(query);            
            rs1.next();
            String ci=rs1.getString("contact_id");
            String fn=rs1.getString("first_name");
            String mn=rs1.getString("middle_name");
            String ln=rs1.getString("last_name");     NAME.setText(fn+" "+mn+" "+ln);
            String gr=rs1.getString("groups");        GROUP1.setText(gr);
            String ad1=rs1.getString("add_line1");
            String ad2=rs1.getString("add_line2");
            String city=rs1.getString("city");
            String state=rs1.getString("state");      
            String pin=rs1.getString("pin");          ADDRESS_F.setText(ad1+" "+ad2+" "+city+" "+state+" "+pin);
            String dob=rs1.getString("dob");          DOB.setText(dob);
            String q1="select mob_number from mobile where contact_id='"+(ci)+"';";
            String q2="select email_id from email where contact_id='"+(ci)+"';";
            int n1=model1.getRowCount();
            for( int i=1;i<=n1;i++)
            {
                model1.removeRow(0);
            }    
            int n2=model2.getRowCount();
            for( int i=1;i<=n2;i++)
            {
                model2.removeRow(0);
            }   
            ResultSet rs2=stmt.executeQuery(q1);
            while(rs2.next())
            {
                String mob=rs2.getString("mob_number");
                model1.addRow(new Object[]{mob});
            }
            ResultSet rs3=stmt.executeQuery(q2);
            while(rs3.next())
            {
                String em=rs3.getString("email_id");
                model2.addRow(new Object[]{em});
            }
            rs1.close();  rs2.close();  rs3.close();         
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }   
      }
    }//GEN-LAST:event_NAMESActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        new SEARCH().show();
        this.dispose();
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEARCH_GROUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEARCH_GROUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEARCH_GROUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEARCH_GROUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEARCH_GROUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ADDRESS;
    private javax.swing.JTextArea ADDRESS_F;
    private javax.swing.JLabel ADDRESS_LABEL;
    private javax.swing.JButton BACK;
    private javax.swing.JLabel CANVAS;
    private javax.swing.JTextField DOB;
    private javax.swing.JTable EMAIL;
    private javax.swing.JScrollPane EMAIL_TABLE;
    private javax.swing.JButton EXIT;
    private javax.swing.JScrollPane GROUP;
    private javax.swing.JTextField GROUP1;
    private javax.swing.JList GROUPS;
    private javax.swing.JLabel GROUP_LABEL;
    private javax.swing.JTable MOBILE;
    private javax.swing.JScrollPane MOBILE_TABLE;
    private javax.swing.JTextField NAME;
    private javax.swing.JComboBox NAMES;
    private javax.swing.JLabel NAME_LABEL;
    private javax.swing.JLabel SEARCH_LABEL;
    private javax.swing.JLabel dob_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
