/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class UPDATE_CONTACT extends javax.swing.JFrame {

    /**
     * Creates new form update_contact
     */
    public UPDATE_CONTACT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NAME_BOX = new javax.swing.JComboBox();
        UPDATE = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        DOB = new javax.swing.JTextField();
        G = new javax.swing.JTextField();
        ADD2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ADD1 = new javax.swing.JTextField();
        ADDRESS2_LABEL = new javax.swing.JLabel();
        CITY = new javax.swing.JTextField();
        CITY_LABEL = new javax.swing.JLabel();
        STATE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        STATE_LABEL = new javax.swing.JLabel();
        PC = new javax.swing.JTextField();
        FN_LABEL = new javax.swing.JLabel();
        ADDRESS1_LABEL = new javax.swing.JLabel();
        PC_LABEL = new javax.swing.JLabel();
        MN_LABEL = new javax.swing.JLabel();
        LN_LABEL = new javax.swing.JLabel();
        MN = new javax.swing.JTextField();
        FN = new javax.swing.JTextField();
        LN = new javax.swing.JTextField();
        GROUP_LABEL = new javax.swing.JLabel();
        dob_label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/address2.jpg"))); // NOI18N

        jPanel1.setLayout(null);

        NAME_BOX.setModel(new DefaultComboBoxModel());
        NAME_BOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME_BOXActionPerformed(evt);
            }
        });
        jPanel1.add(NAME_BOX);
        NAME_BOX.setBounds(20, 150, 240, 30);

        UPDATE.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        UPDATE.setText("UPDATE CONTACT");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        jPanel1.add(UPDATE);
        UPDATE.setBounds(40, 240, 200, 30);

        BACK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel1.add(BACK);
        BACK.setBounds(80, 330, 110, 30);

        DOB.setToolTipText("yyyy-mm-dd");
        jPanel1.add(DOB);
        DOB.setBounds(450, 370, 230, 30);
        jPanel1.add(G);
        G.setBounds(450, 330, 230, 30);
        jPanel1.add(ADD2);
        ADD2.setBounds(450, 170, 230, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("UPDATING A CONTACT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 10, 270, 28);
        jPanel1.add(ADD1);
        ADD1.setBounds(450, 130, 230, 30);

        ADDRESS2_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ADDRESS2_LABEL.setText("ADDRESS LINE 2");
        jPanel1.add(ADDRESS2_LABEL);
        ADDRESS2_LABEL.setBounds(320, 180, 110, 15);
        jPanel1.add(CITY);
        CITY.setBounds(450, 210, 230, 30);

        CITY_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CITY_LABEL.setText("CITY");
        jPanel1.add(CITY_LABEL);
        CITY_LABEL.setBounds(320, 220, 50, 15);

        STATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STATEActionPerformed(evt);
            }
        });
        jPanel1.add(STATE);
        STATE.setBounds(450, 250, 230, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel6.setText("SORRY BUT MOBILE NUMBERS AND EMAIL ID UPDATION NOT ALLOWED");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 410, 670, 30);

        STATE_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        STATE_LABEL.setText("STATE");
        jPanel1.add(STATE_LABEL);
        STATE_LABEL.setBounds(320, 260, 60, 15);
        jPanel1.add(PC);
        PC.setBounds(450, 290, 230, 30);

        FN_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FN_LABEL.setText("FIRST NAME");
        jPanel1.add(FN_LABEL);
        FN_LABEL.setBounds(320, 20, 80, 15);

        ADDRESS1_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ADDRESS1_LABEL.setText("ADDRESS LINE 1");
        jPanel1.add(ADDRESS1_LABEL);
        ADDRESS1_LABEL.setBounds(320, 140, 110, 15);

        PC_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PC_LABEL.setText("PIN CODE");
        jPanel1.add(PC_LABEL);
        PC_LABEL.setBounds(320, 300, 60, 15);

        MN_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MN_LABEL.setText("MIDDLE NAME");
        jPanel1.add(MN_LABEL);
        MN_LABEL.setBounds(320, 60, 87, 10);

        LN_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LN_LABEL.setText("LAST NAME");
        jPanel1.add(LN_LABEL);
        LN_LABEL.setBounds(320, 100, 70, 10);
        jPanel1.add(MN);
        MN.setBounds(450, 50, 230, 30);
        jPanel1.add(FN);
        FN.setBounds(450, 10, 230, 30);
        jPanel1.add(LN);
        LN.setBounds(449, 90, 230, 30);

        GROUP_LABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GROUP_LABEL.setText("GROUP");
        jPanel1.add(GROUP_LABEL);
        GROUP_LABEL.setBounds(320, 340, 60, 15);

        dob_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dob_label.setText("DATE OF BIRTH");
        dob_label.setToolTipText("yyyy-mm-dd");
        jPanel1.add(dob_label);
        dob_label.setBounds(320, 380, 100, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("SELECT THE CONTACT TO UPDATE");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 80, 250, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 720, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NAME_BOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME_BOXActionPerformed
        try
        {
            String mi="";
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/address","root","modi");
            Statement stmt=(Statement)con.createStatement();
            String st=(String)NAME_BOX.getSelectedItem();
            int l=st.length();
            String s=st.substring(l-6,l-1);
            String query="select * from contact where contact_id='"+s+"';";
            ResultSet rs1=stmt.executeQuery(query);
            rs1.next();
            String ci=rs1.getString("contact_id");     
            String fn=rs1.getString("first_name");      FN.setText(fn);
            String mn=rs1.getString("middle_name");     MN.setText(mn);
            String ln=rs1.getString("last_name");       LN.setText(ln);     
            String gr=rs1.getString("groups");          G.setText(gr);  
            String ad1=rs1.getString("add_line1");      ADD1.setText(ad1);
            String ad2=rs1.getString("add_line2");      ADD2.setText(ad2);
            String city=rs1.getString("city");          CITY.setText(city);
            String state=rs1.getString("state");        STATE.setText(state);
            String pin=rs1.getString("pin");            PC.setText(pin);   
            String dob=rs1.getString("dob");            DOB.setText(dob);     
            rs1.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_NAME_BOXActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        try
        {
            Class.forName("java.sql.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/address","root","modi");
            Statement stmt=(Statement) con.createStatement();
            int m=JOptionPane.showConfirmDialog(this,"DO YOU REALLY WANT TO UPDATE THIS CONTACT?","MESSAGE",JOptionPane.YES_NO_OPTION);
            if(m==0)
            {
                String st=(String)NAME_BOX.getSelectedItem();
                int l=st.length();
                String s=st.substring(l-6,l-1);
                String fn1=FN.getText();
                String mn1=MN.getText();
                String ln1=LN.getText();     
                String g1=G.getText();  
                String add1=ADD1.getText();
                String add2=ADD2.getText();
                String cit=CITY.getText();
                String sta=STATE.getText();
                String pco=PC.getText();   
                String db=DOB.getText();
                String query="update contact set first_name='"+(fn1)+"',middle_name='"+(mn1)+"',last_name='"+(ln1)+"',groups='"+(g1)+"',add_line1='"+(add1)+"',add_line2='"+(add2)+"',city='"+(cit)+"',state='"+(sta)+"',dob='"+(db)+"',pin='"+(pco)+"' where contact_id='"+(s)+"';";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "CONTACT UPDATED");
                            
            
                    String que="select * from contact where contact_id='"+(s)+"';";
                    ResultSet rs5=stmt.executeQuery(que);
                    rs5.next();
                    String fn=rs5.getString("first_name");      FN.setText(fn);
                    String mn=rs5.getString("middle_name");     MN.setText(mn);
                    String ln=rs5.getString("last_name");       LN.setText(ln);     
                    String gr=rs5.getString("groups");          G.setText(gr);  
                    String ad1=rs5.getString("add_line1");      ADD1.setText(ad1);
                    String ad2=rs5.getString("add_line2");      ADD2.setText(ad2);
                    String city=rs5.getString("city");          CITY.setText(city);
                    String state=rs5.getString("state");        STATE.setText(state);
                    String pin=rs5.getString("pin");            PC.setText(pin);   
                    String dob=rs5.getString("dob");            DOB.setText(dob);     
                    rs5.close();                
            }
            else JOptionPane.showMessageDialog(this,"CONTACT NOT UPDATED");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"CONTACT NOT UPDATED");
        }

    }//GEN-LAST:event_UPDATEActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        new FIRST_PAGE().show();
        this.dispose();
    }//GEN-LAST:event_BACKActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try
       {
           DefaultComboBoxModel model=(DefaultComboBoxModel)NAME_BOX.getModel();
           Class.forName("java.sql.Driver");
           String q1="";
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost/address","root","modi");
           Statement stmt=con.createStatement();      
           q1=" select concat(first_name,' ',middle_name,' ',last_name,' ','(',(contact_id),')') from contact order by first_name;";
           ResultSet rs=stmt.executeQuery(q1);
           model.removeAllElements();
           while(rs.next())
           {
               String c=rs.getString("concat(first_name,' ',middle_name,' ',last_name,' ','(',(contact_id),')')");
               model.addElement(c);
           }
           
       }
    catch(Exception e)
       {
        JOptionPane.showMessageDialog(this, e.getMessage());
       }
    }//GEN-LAST:event_formWindowOpened

    private void STATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STATEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STATEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATE_CONTACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATE_CONTACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATE_CONTACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATE_CONTACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATE_CONTACT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADD1;
    private javax.swing.JTextField ADD2;
    private javax.swing.JLabel ADDRESS1_LABEL;
    private javax.swing.JLabel ADDRESS2_LABEL;
    private javax.swing.JButton BACK;
    private javax.swing.JTextField CITY;
    private javax.swing.JLabel CITY_LABEL;
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField FN;
    private javax.swing.JLabel FN_LABEL;
    private javax.swing.JTextField G;
    private javax.swing.JLabel GROUP_LABEL;
    private javax.swing.JTextField LN;
    private javax.swing.JLabel LN_LABEL;
    private javax.swing.JTextField MN;
    private javax.swing.JLabel MN_LABEL;
    private javax.swing.JComboBox NAME_BOX;
    private javax.swing.JTextField PC;
    private javax.swing.JLabel PC_LABEL;
    private javax.swing.JTextField STATE;
    private javax.swing.JLabel STATE_LABEL;
    private javax.swing.JButton UPDATE;
    private javax.swing.JLabel dob_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
